import { Permission } from "../domain/value-objects/permission.type";

export const DEFAULT_ADMIN_PERMISSIONS: Permission[] = [
  "users:read",
  "users:create",
  "users:update",
  "users:delete",
  "roles:read",
  "roles:create",
  "roles:update",
  "roles:delete",
  "products:read",
  "products:create",
  "products:update",
  "products:delete",
  "categories:read",
  "categories:create",
  "categories:update",
  "categories:delete",
  "attributes:read",
  "attributes:create",
  "attributes:update",
  "attributes:delete",
  "attribute-values:read",
  "attribute-values:create",
  "attribute-values:update",
  "attribute-values:delete",
  "attribute-sets:read",
  "attribute-sets:create",
  "attribute-sets:update",
  "attribute-sets:delete",
  "storage:read",
  "storage:create",
  "storage:update",
  "storage:delete",
  "translations:read",
  "translations:create",
  "translations:update",
  "translations:delete",
  "translations:manage",
  // Multi-seller marketplace permissions
  "stores:read",
  "stores:create",
  "stores:update",
  "stores:delete",
  "stores:approve",
  "stores:suspend",
  "orders:read",
  "orders:create",
  "orders:update",
  "orders:delete",
  "commissions:read",
  "commissions:create",
  "commissions:update",
  "commissions:delete",
  "commissions:manage",
  "shipments:read",
  "shipments:create",
  "shipments:update",
  "shipments:delete",
  "marketplace:settings",
  "analytics:read",
];

export const DEFAULT_USER_PERMISSIONS: Permission[] = [
  "users:read",
  "products:read",
  "categories:read",
  "attributes:read",
  "attribute-values:read",
  "attribute-sets:read",
  "storage:read",
];

export const DEFAULT_SELLER_PERMISSIONS: Permission[] = [
  "users:read",
  "products:read",
  "products:create",
  "products:update",
  "products:delete",
  "categories:read",
  "attributes:read",
  "attribute-values:read",
  "attribute-sets:read",
  "storage:read",
  "storage:create",
  "storage:update",
  "translations:read",
  // Seller-specific permissions
  "stores:read",
  "stores:create",
  "stores:update",
  "orders:read",
  "commissions:read",
  "shipments:read",
  "shipments:create",
  "shipments:update",
  "analytics:read",
];

export const DEFAULT_JWT_SECRET = "dev_secret_change_me";

export const DEFAULT_USER_PASSWORD = "secret";
